# Generated by Django 3.2.13 on 2022-07-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placelocation',
            name='iso_3166_2_lvl4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='placelocation',
            name='location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placelocation',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='placelocation',
            name='subdistrict',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='iso_3166_2_lvl4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='subdistrict',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
