# Generated by Django 3.2.13 on 2022-07-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20220712_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placelocation',
            old_name='postcode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='userlocation',
            old_name='postcode',
            new_name='postal_code',
        ),
    ]
