# Generated by Django 3.2.13 on 2022-07-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20220721_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='placelocation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
