# Generated by Django 3.2.13 on 2022-07-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20220721_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseLocation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('district', 'District'), ('city', 'City'), ('subregion', 'Subregion'), ('region', 'Region')], max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('country_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=23)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=23)),
            ],
        ),
    ]
