# Generated by Django 3.2.13 on 2022-07-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_chooselocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chooselocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
