# Generated by Django 3.2.13 on 2022-07-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_chooselocation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chooselocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='chooselocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True),
        ),
    ]
