# Generated by Django 3.2.13 on 2022-07-23 19:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20220723_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='chooselocation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
