# Generated by Django 3.2.13 on 2022-07-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_chooselocation_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chooselocation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
