# Generated by Django 3.2.13 on 2022-06-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_userdevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdevice',
            old_name='device',
            new_name='device_name',
        ),
        migrations.RenameField(
            model_name='userdevice',
            old_name='token',
            new_name='firebase_token',
        ),
    ]
