# Generated by Django 3.2.13 on 2022-06-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20220622_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='topic',
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
