# Generated by Django 3.2.13 on 2022-06-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_auto_20220623_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='text',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='image',
        ),
    ]
