# Generated by Django 3.2.13 on 2022-06-23 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0011_auto_20220623_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
        migrations.AddField(
            model_name='notificationsend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationsend',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='notification.topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationsend',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notification.notification'),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
