# Generated by Django 3.2.13 on 2022-06-30 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0065_auto_20220615_0522'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0015_auto_20220627_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('place', 'place'), ('user', 'user')], default='place', max_length=10)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('ordering', models.SmallIntegerField(default=0)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('writer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='inline_references',
            field=models.ManyToManyField(related_name='by_inline_notifications', to='notification.Reference'),
        ),
        migrations.AddField(
            model_name='notification',
            name='main_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='by_main_notifications', to='notification.reference'),
        ),
    ]
