# Generated by Django 3.2.13 on 2022-04-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type_of_people_around',
            field=models.TextField(blank=True, null=True),
        ),
    ]
