# Generated by Django 4.0.3 on 2022-03-19 13:20

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import place.models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate', models.CharField(blank=True, choices=[('Tropical', 'Tropical'), ('Dry', 'Dry'), ('Mild', 'Mild'), ('Continental', 'Continental'), ('Polar', 'Polar')], max_length=255)),
                ('climate_description', models.TextField(blank=True, null=True)),
                ('tips_for_every_season', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.RemoveField(
            model_name='place',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='place',
            name='climate_description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='region',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tips_for_every_season',
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=place.models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(choices=[('asia', 'Asia'), ('africa', 'Africa'), ('europe', 'Europe'), ('north america', 'North America'), ('south america', 'South America'), ('australia/oceania', 'Australia/Oceania'), ('antarctica', 'Antarctica')], default='Asia', max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='place.place')),
            ],
        ),
    ]
