# Generated by Django 4.0.3 on 2022-03-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
    ]
