# Generated by Django 4.0.3 on 2022-03-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='places',
        ),
        migrations.AddField(
            model_name='groups',
            name='places',
            field=models.ManyToManyField(to='place.place'),
        ),
    ]
