# Generated by Django 4.0.3 on 2022-03-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_climaticconditions_remove_place_nearest_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='climate_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
