# Generated by Django 4.0.3 on 2022-03-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_remove_groups_places_groups_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='places',
            field=models.ManyToManyField(blank=True, to='place.place', verbose_name='places'),
        ),
    ]
