# Generated by Django 4.0.3 on 2022-03-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_remove_groups_places_groups_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='place',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='places',
            field=models.ManyToManyField(blank=True, to='place.place', verbose_name='places'),
        ),
    ]
