# Generated by Django 4.0.3 on 2022-03-20 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_civilization_safe_turist_typeofterrain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='currency',
            new_name='how_to_get_there',
        ),
        migrations.RemoveField(
            model_name='place',
            name='currency_buying_advice',
        ),
        migrations.RemoveField(
            model_name='place',
            name='internet',
        ),
        migrations.RemoveField(
            model_name='place',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='place',
            name='local_kitchen',
        ),
        migrations.RemoveField(
            model_name='place',
            name='pay_online_or_by_card',
        ),
        migrations.RemoveField(
            model_name='place',
            name='price_and_average_kitchen',
        ),
        migrations.RemoveField(
            model_name='place',
            name='simcards',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tourist_population_per_season_autumn',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tourist_population_per_season_spring',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tourist_population_per_season_summer',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tourist_population_per_season_winter',
        ),
        migrations.RemoveField(
            model_name='place',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='place',
            name='types_of_ecosystem',
        ),
        migrations.RemoveField(
            model_name='place',
            name='types_of_ecosystem_description',
        ),
        migrations.RemoveField(
            model_name='typeofterrain',
            name='terrain',
        ),
        migrations.AddField(
            model_name='typeofterrain',
            name='types_of_ecosystem',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='typeofterrain',
            name='types_of_ecosystem_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Socialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.TextField(blank=True, null=True)),
                ('currency_buying_advice', models.TextField(blank=True, null=True)),
                ('simcards', models.BooleanField()),
                ('internet', models.TextField(blank=True, null=True)),
                ('pay_online_or_by_card', models.TextField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socializations', to='place.place')),
            ],
        ),
        migrations.CreateModel(
            name='NaturalPhenomena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natural_phenomena', to='place.place')),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entertainments', to='place.place')),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.TextField(blank=True, null=True)),
                ('local_kitchen', models.TextField(blank=True, null=True)),
                ('price_and_average_kitchen', models.TextField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisines', to='place.place')),
            ],
        ),
    ]
