# Generated by Django 4.0.3 on 2022-03-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_groups_image_place_images_alter_groups_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
