# Generated by Django 4.0.3 on 2022-03-29 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_alter_location_city_alter_location_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='place',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='place.place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ManyToManyField(blank=True, to='place.category'),
        ),
    ]
