# Generated by Django 4.0.3 on 2022-03-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_rename_currency_place_how_to_get_there_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='place.place')),
            ],
        ),
    ]
