# Generated by Django 4.0.3 on 2022-03-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_alter_location_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
