# Generated by Django 4.0.3 on 2022-03-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_vibe'),
    ]

    operations = [
        migrations.AddField(
            model_name='vibe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
