# Generated by Django 3.2.13 on 2022-04-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoptions',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_option', to='place.place'),
        ),
    ]
