# Generated by Django 4.0.3 on 2022-03-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_remove_place_rating_place_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='rate',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
    ]
