# Generated by Django 3.2.13 on 2022-04-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_alter_accommodationoptions_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccommodationOptions',
            new_name='AccommodationOption',
        ),
        migrations.RenameModel(
            old_name='FloraAndFauna',
            new_name='FloraFauna',
        ),
    ]
