# Generated by Django 4.0.3 on 2022-03-20 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_vibe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloraAndFauna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flora', models.TextField(blank=True, null=True)),
                ('flora_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('fauna', models.TextField(blank=True, null=True)),
                ('fauna_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flora_fauna', to='place.place')),
            ],
        ),
    ]
