# Generated by Django 4.0.3 on 2022-03-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_alter_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeOfTerrain',
            new_name='GeographicalFeature',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='type_of_terrain',
            new_name='geographical_feature',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='type_of_terrain_description',
            new_name='geographical_feature_description',
        ),
    ]
