# Generated by Django 4.0.3 on 2022-03-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_remove_place_images_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
    ]
