# Generated by Django 3.2.13 on 2022-04-25 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_auto_20220421_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimaticCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255)),
                ('climate', models.CharField(choices=[('Tropical', 'Tropical'), ('Dry', 'Dry'), ('Mild', 'Mild'), ('Continental', 'Continental'), ('Polar', 'Polar')], max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='userplacerelation',
            old_name='description_rating',
            new_name='rating_description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='category',
        ),
        migrations.RemoveField(
            model_name='place',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='place',
            name='climate_description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='geographical_feature_description',
        ),
        migrations.AddField(
            model_name='geographicalfeature',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='categories',
            field=models.ManyToManyField(blank=True, to='place.Category'),
        ),
        migrations.AlterField(
            model_name='accommodationoption',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_options', to='place.place'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='place.place'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisines', to='place.typecuisine'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisines', to='place.place'),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entertainments', to='place.place'),
        ),
        migrations.AlterField(
            model_name='florafauna',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flora_faunas', to='place.place'),
        ),
        migrations.AlterField(
            model_name='group',
            name='place',
            field=models.ManyToManyField(blank=True, related_name='groups', to='place.Place', verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='interestingfacts',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesting_facts', to='place.place'),
        ),
        migrations.AlterField(
            model_name='location',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='place.place'),
        ),
        migrations.AlterField(
            model_name='mustsee',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='must_sees', to='place.place'),
        ),
        migrations.AlterField(
            model_name='naturalphenomena',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natural_phenomenas', to='place.place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='pay_online_or_by_card',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='views',
            field=models.ManyToManyField(through='place.UserPlaceRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='practicalinformation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_informations', to='place.place'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safes', to='place.place'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='place.place'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='place.typetransport'),
        ),
        migrations.AlterField(
            model_name='uniquenessplace',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uniqueness_places', to='place.place'),
        ),
        migrations.AlterField(
            model_name='vibe',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='place.place'),
        ),
        migrations.AlterField(
            model_name='wheretotakeapicture',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where_to_take_a_pictures', to='place.place'),
        ),
        migrations.DeleteModel(
            name='ClimaticConditions',
        ),
        migrations.AddField(
            model_name='place',
            name='climatic_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.climaticcondition'),
        ),
    ]
