# Generated by Django 3.2.13 on 2022-04-25 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_auto_20220425_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(default='Place name', max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='views',
            field=models.ManyToManyField(blank=True, through='place.UserPlaceRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transport',
            name='comfortable',
            field=models.CharField(choices=[('Very Comfortable', 'Very Comfortable'), ('Comfortable', 'Comfortable'), ('Average', 'Average'), ('Durable', 'Durable'), ('Totally Uncomfortable', 'Totally Uncomfortable')], max_length=255),
        ),
    ]
