# Generated by Django 4.0.3 on 2022-03-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_alter_groups_places'),
        ('place', '0009_rename_groups_group'),
    ]

    operations = [
    ]
