# Generated by Django 4.0.3 on 2022-03-31 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_rename_typeofterrain_geographicalfeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='type_cuisine',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tourist_population_per_season_autumn',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tourist_population_per_season_spring',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tourist_population_per_season_summer',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tourist_population_per_season_winter',
        ),
        migrations.RemoveField(
            model_name='place',
            name='turist_description',
        ),
        migrations.AddField(
            model_name='place',
            name='turist_rating',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='place',
            name='type_of_people_around',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='TypeOfPeople',
        ),
        migrations.AddField(
            model_name='practicalinformation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_informations', to='place.place'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.typecuisine'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.typetransport'),
        ),
    ]
