# Generated by Django 4.0.3 on 2022-03-16 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_rename_groups_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='nickname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='places', to='place.place', verbose_name='places'),
        ),
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='place.place'),
        ),
    ]
