# Generated by Django 4.0.3 on 2022-03-20 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_remove_place_rating_satisfaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climaticconditions',
            name='climate',
            field=models.CharField(choices=[('Tropical', 'Tropical'), ('Dry', 'Dry'), ('Mild', 'Mild'), ('Continental', 'Continental'), ('Polar', 'Polar')], max_length=255),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfactions', to='place.place'),
        ),
    ]
