# Generated by Django 4.0.3 on 2022-03-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_place_description_place_nickname_alter_group_places_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='continent',
            field=models.CharField(choices=[('asia', 'Asia'), ('africa', 'Africa'), ('europe', 'Europe'), ('north america', 'North America'), ('south america', 'South America'), ('australia/oceania', 'Australia/Oceania'), ('antarctica', 'Antarctica')], default='Asia', max_length=20),
        ),
    ]
