# Generated by Django 4.0.3 on 2022-03-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_alter_climaticconditions_climate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='civilization',
            name='type_of_people_around',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.typeofpeople'),
        ),
    ]
