# Generated by Django 4.0.3 on 2022-04-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_practicalinformation_typecuisine_typetransport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=13),
        ),
    ]
