# Generated by Django 4.0.3 on 2022-04-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_alter_cuisine_price_alter_transport_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typecuisine',
            old_name='type',
            new_name='name',
        ),
    ]
