# Generated by Django 4.0.3 on 2022-03-16 17:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_place_continent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='location',
        ),
        migrations.AddField(
            model_name='place',
            name='country_of_work',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
