# Generated by Django 4.0.3 on 2022-03-20 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_alter_civilization_type_of_people_around'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfaction',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
