# Generated by Django 4.0.3 on 2022-03-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_remove_place_location_place_country_of_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='country_of_work',
            new_name='country',
        ),
    ]
