# Generated by Django 4.0.3 on 2022-04-01 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_rename_type_typecuisine_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typecuisine',
            old_name='name',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='place.typecuisine'),
        ),
    ]
