# Generated by Django 4.0.3 on 2022-04-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0013_rename_name_typecuisine_type_alter_cuisine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='interestingfacts',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='mustsee',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='naturalphenomena',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='uniquenessplace',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vibe',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='wheretotakeapicture',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
