# Generated by Django 3.2.13 on 2022-04-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0013_alter_group_places'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
