# Generated by Django 4.0.3 on 2022-03-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0013_rename_country_of_work_place_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='nearest_place',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='region',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
