# Generated by Django 4.0.3 on 2022-03-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0014_alter_location_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialization',
            name='place',
        ),
        migrations.RemoveField(
            model_name='turist',
            name='place',
        ),
        migrations.RenameField(
            model_name='floraandfauna',
            old_name='fauna_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='local_kitchen',
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='price_and_average_kitchen',
        ),
        migrations.RemoveField(
            model_name='floraandfauna',
            name='fauna',
        ),
        migrations.RemoveField(
            model_name='floraandfauna',
            name='flora',
        ),
        migrations.RemoveField(
            model_name='floraandfauna',
            name='flora_image',
        ),
        migrations.AddField(
            model_name='cuisine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='type_cuisine',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='floraandfauna',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='floraandfauna',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='culture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='currency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='currency_buying_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='internet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='nation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='pay_online_or_by_card',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='simcards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='tourist_population_per_season_autumn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='tourist_population_per_season_spring',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='tourist_population_per_season_summer',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='tourist_population_per_season_winter',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='turist_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='type_of_people_around',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='civilizations', to='place.typeofpeople'),
        ),
        migrations.AddField(
            model_name='safe',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Civilization',
        ),
        migrations.DeleteModel(
            name='Socialization',
        ),
        migrations.DeleteModel(
            name='Turist',
        ),
    ]
