# Generated by Django 3.2.13 on 2022-04-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0014_delete_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('places', models.ManyToManyField(blank=True, to='place.Place')),
            ],
        ),
    ]
