# Generated by Django 4.0.3 on 2022-03-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0015_alter_place_city_alter_place_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(default='City', max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='region',
            field=models.CharField(default='Region', max_length=255),
        ),
    ]
