# Generated by Django 4.0.3 on 2022-03-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0015_remove_socialization_place_remove_turist_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categories', to='place.category', verbose_name='categories'),
        ),
    ]
