# Generated by Django 3.2.13 on 2022-04-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0015_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
