# Generated by Django 3.2.13 on 2022-04-26 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0016_place_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images/places/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories/'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cuisines/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/custom_user/'),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/entertainments/'),
        ),
        migrations.AlterField(
            model_name='florafauna',
            name='image',
            field=models.ImageField(default=None, upload_to='images/flora_faunas/'),
        ),
        migrations.AlterField(
            model_name='interestingfacts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/interesting_facts/'),
        ),
        migrations.AlterField(
            model_name='mustsee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/must_sees/'),
        ),
        migrations.AlterField(
            model_name='naturalphenomena',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/natural_phenomenas/'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/transports/'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='place.place'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='place.typetransport'),
        ),
        migrations.AlterField(
            model_name='uniquenessplace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/uniqueness_places/'),
        ),
        migrations.AlterField(
            model_name='vibe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/vibes/'),
        ),
        migrations.AlterField(
            model_name='wheretotakeapicture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/where_to_take_a_pictures/'),
        ),
    ]
