# Generated by Django 4.0.3 on 2022-04-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0016_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bookmark_place',
            field=models.ManyToManyField(blank=True, related_name='bookmark_places', to='place.place', verbose_name='bookmark_places'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
