# Generated by Django 4.0.3 on 2022-03-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0016_alter_place_city_alter_place_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.RemoveField(
            model_name='place',
            name='region',
        ),
    ]
