# Generated by Django 4.0.3 on 2022-03-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0017_remove_place_city_remove_place_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='City', max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='region',
            field=models.CharField(default='Region', max_length=255),
        ),
    ]
