# Generated by Django 4.0.3 on 2022-04-05 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0018_remove_customuser_bookmark_place_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bookmark_place',
            field=models.ManyToManyField(blank=True, related_name='bookmark_places', to='place.place', verbose_name='bookmark_places'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_bookmarks', to='place.place'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
