# Generated by Django 4.0.3 on 2022-03-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0018_place_city_place_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
