# Generated by Django 4.0.3 on 2022-03-22 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('place', '0018_userplacerelation_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='views',
            field=models.ManyToManyField(related_name='views', through='place.UserPlaceRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
