# Generated by Django 4.0.3 on 2022-03-22 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0019_place_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplacerelation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_place', to='place.place'),
        ),
    ]
