# Generated by Django 4.0.3 on 2022-04-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0019_customuser_bookmark_place_alter_bookmark_place_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
