# Generated by Django 4.0.3 on 2022-04-05 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0020_delete_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='bookmark_place',
            field=models.ManyToManyField(blank=True, related_name='bookmark_customuser', to=settings.AUTH_USER_MODEL, verbose_name='bookmark_customuser'),
        ),
    ]
