# Generated by Django 4.0.3 on 2022-03-22 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0020_alter_userplacerelation_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='safe',
            name='rating_danger',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
