# Generated by Django 3.2.13 on 2022-05-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0020_alter_transport_comfortable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='continent',
            field=models.CharField(choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Australia/Oceania', 'Australia/Oceania'), ('Antarctica', 'Antarctica')], default='Asia', max_length=20),
        ),
        migrations.AlterField(
            model_name='safe',
            name='how_dangerous',
            field=models.CharField(blank=True, choices=[('Very safe', 'Very safe'), ('Safe', 'Safe'), ('Average', 'Average'), ('Somewhat dangerous', 'Somewhat dangerous'), ('Dangerous', 'Dangerous')], max_length=255),
        ),
        migrations.AlterField(
            model_name='transport',
            name='comfortable',
            field=models.CharField(blank=True, choices=[('Very comfortable', 'Very comfortable'), ('Comfortable', 'Comfortable'), ('Average', 'Average'), ('Durable', 'Durable'), ('Totally uncomfortable', 'Totally uncomfortable')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
