# Generated by Django 4.0.3 on 2022-03-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0021_remove_place_location_place_city_place_continent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='population',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
