# Generated by Django 3.2.13 on 2022-05-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0021_auto_20220503_0648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='accommodationoption',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accommodationoption',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='florafauna',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/flora_faunas/'),
        ),
        migrations.AlterField(
            model_name='mustsee',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='places', to='place.Category'),
        ),
    ]
