# Generated by Django 4.0.3 on 2022-04-05 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0021_place_bookmark_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bookmark_place',
        ),
        migrations.RemoveField(
            model_name='place',
            name='bookmark_place',
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_bookmarks', to='place.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
