# Generated by Django 4.0.3 on 2022-03-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0022_alter_place_population_alter_place_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='type_of_people_around',
            field=models.CharField(blank=True, choices=[('ambitious and passionate people', 'Ambitious and passionate people'), ('the doers', 'The doers'), ('the problem solvers', 'The problem solvers'), ('those who are on a similar journey as you', 'Those who are on a similar journey as you'), ('those who can inspire you and be your role model', 'Those who can inspire you and be your role model'), ('those who help you tap your full potential and bring out the best in you', 'Those who help you tap your full potential and bring out the best in you'), ('those who can provide a genuine feedback', 'Those who can provide a genuine feedback'), ('those who can help you keep happy, upbeat and positive', 'Those who can help you keep happy, upbeat and positive'), ('the ‘forward moving’ people', 'The ‘forward moving’ people')], max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='nearest_place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
