# Generated by Django 4.0.3 on 2022-03-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0023_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoptions',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=13),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=13),
        ),
    ]
