# Generated by Django 4.0.3 on 2022-03-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0024_place_climate_place_climate_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='nearest_airport',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='tourist_population_per_season_autumn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='tourist_population_per_season_spring',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='tourist_population_per_season_summer',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='tourist_population_per_season_winter',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='transport',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='type_of_transport',
            field=models.ManyToManyField(blank=True, to='place.transport'),
        ),
    ]
