# Generated by Django 3.2.13 on 2022-05-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0024_auto_20220505_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(default=1, upload_to='images/places/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='place_images', to='place.place'),
            preserve_default=False,
        ),
    ]
