# Generated by Django 4.0.3 on 2022-03-23 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0024_alter_accommodationoptions_price_alter_cuisine_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestingFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesting_facts', to='place.place')),
            ],
        ),
    ]
