# Generated by Django 3.2.13 on 2022-05-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0025_auto_20220507_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='nearest_place',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
