# Generated by Django 4.0.3 on 2022-03-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0025_transport_place_nearest_airport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type_of_transport',
            field=models.ManyToManyField(blank=True, related_name='transports', to='place.transport', verbose_name='transports'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.CharField(choices=[('Walking', 'Walking'), ('Biking', 'Biking'), ('Cars', 'Cars'), ('Trains', 'Trains'), ('Buses', 'Buses'), ('Boats', 'Boats'), ('Subways', 'Subways'), ('Aerial Tramways', 'Aerial Tramways'), ('Flying', 'Flying'), ('Funiculars', 'Funiculars')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
