# Generated by Django 4.0.3 on 2022-03-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0026_alter_floraandfauna_image_alter_floraandfauna_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mustsee',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='wheretotakeapicture',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
