# Generated by Django 3.2.13 on 2022-05-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0026_auto_20220508_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='nearest_place',
            field=models.TextField(blank=True, null=True),
        ),
    ]
