# Generated by Django 4.0.3 on 2022-03-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0026_alter_place_type_of_transport_alter_transport_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='kitchen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='local_kitchen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='price_and_average_kitchen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='accommodation_options',
            field=models.ManyToManyField(blank=True, related_name='accommodationOptions', to='place.accommodationoptions', verbose_name='accommodationOptions'),
        ),
    ]
