# Generated by Django 4.0.3 on 2022-03-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0027_accommodationoptions_place_kitchen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MustSee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='UniquenessPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='WhereToTakeAPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='must_see',
            field=models.ManyToManyField(blank=True, related_name='must_see', to='place.mustsee', verbose_name='must_see'),
        ),
        migrations.AddField(
            model_name='place',
            name='uniqueness_place',
            field=models.ManyToManyField(blank=True, related_name='uniqueness_place', to='place.uniquenessplace', verbose_name='uniqueness_place'),
        ),
        migrations.AddField(
            model_name='place',
            name='where_to_take_a_picture',
            field=models.ManyToManyField(blank=True, related_name='where_to_take_a_picture', to='place.wheretotakeapicture', verbose_name='where_to_take_a_picture'),
        ),
    ]
