# Generated by Django 4.0.3 on 2022-03-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0027_alter_mustsee_name_alter_wheretotakeapicture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoptions',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='naturalphenomena',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='safe',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.CharField(choices=[('Walking', 'Walking'), ('Biking', 'Biking'), ('Cars', 'Cars'), ('Trains', 'Trains'), ('Buses', 'Buses'), ('Boats', 'Boats'), ('Subways', 'Subways'), ('Aerial Tramways', 'Aerial Tramways'), ('Flying', 'Flying'), ('Funiculars', 'Funiculars')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='uniquenessplace',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='vibe',
            name='vibe',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
