# Generated by Django 4.0.3 on 2022-03-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0028_mustsee_uniquenessplace_wheretotakeapicture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='currency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='currency_buying_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='internet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='pay_online_or_by_card',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='simcards',
            field=models.TextField(blank=True, null=True),
        ),
    ]
