# Generated by Django 4.0.3 on 2022-03-24 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place', '0028_alter_accommodationoptions_name_alter_cuisine_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='writer_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='writer_user', to=settings.AUTH_USER_MODEL, verbose_name='writer_user'),
            preserve_default=False,
        ),
    ]
