# Generated by Django 3.2.13 on 2022-05-10 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0028_auto_20220509_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='books',
            field=models.ManyToManyField(blank=True, default=None, related_name='book', to=settings.AUTH_USER_MODEL),
        ),
    ]
