# Generated by Django 4.0.3 on 2022-03-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0029_place_writer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='home_page',
            field=models.BooleanField(default=False),
        ),
    ]
