# Generated by Django 4.0.3 on 2022-03-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_merge_20220316_1557'),
        ('place', '0029_place_currency_place_currency_buying_advice_and_more'),
    ]

    operations = [
    ]
