# Generated by Django 3.2.13 on 2022-05-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0029_place_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='books',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
