# Generated by Django 4.0.3 on 2022-04-07 17:04

import django.contrib.gis.geos.point
from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0031_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=django.contrib.gis.geos.point.Point(1.0, 1.0), max_length=63),
        ),
    ]
