# Generated by Django 3.2.13 on 2022-05-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0032_place_is_bookmarked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='user',
            new_name='writer_user',
        ),
    ]
