# Generated by Django 4.0.3 on 2022-04-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0033_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typetransport',
            old_name='type',
            new_name='name',
        ),
    ]
