# Generated by Django 4.0.3 on 2022-04-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0034_rename_type_typetransport_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vibe',
            old_name='vibe',
            new_name='name',
        ),
    ]
