# Generated by Django 4.0.3 on 2022-04-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0034_worldborder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
