# Generated by Django 3.2.13 on 2022-05-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0034_achievement_ownedachievement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ownedachievement',
            unique_together={('writer_user', 'achievement')},
        ),
    ]
