# Generated by Django 4.0.3 on 2022-04-14 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0035_rename_vibe_vibe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoptions',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_Option', to='place.place'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_bookmark', to='place.place'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisine', to='place.place'),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entertainment', to='place.place'),
        ),
        migrations.AlterField(
            model_name='group',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='places', to='place.place', verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='interestingfacts',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesting_fact', to='place.place'),
        ),
        migrations.AlterField(
            model_name='location',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='place.place'),
        ),
        migrations.AlterField(
            model_name='practicalinformation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_information', to='place.place'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe', to='place.place'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='place.place'),
        ),
        migrations.AlterField(
            model_name='vibe',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibe', to='place.place'),
        ),
    ]
