# Generated by Django 3.2.13 on 2022-05-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0035_alter_ownedachievement_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='how_to_own',
            field=models.TextField(blank=True),
        ),
    ]
