# Generated by Django 3.2.13 on 2022-05-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0036_achievement_how_to_own'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ownedachievement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ownedachievement',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='ownedachievement',
            name='writer_user',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='OwnedAchievement',
        ),
    ]
