# Generated by Django 3.2.13 on 2022-05-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0037_auto_20220512_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='bookmarks',
            new_name='bookmarked_users',
        ),
    ]
