# Generated by Django 4.0.3 on 2022-04-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0037_customuser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
