# Generated by Django 4.0.3 on 2022-04-15 14:48

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0039_rename_profile_pic_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='coordinate',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0.0, 0.0, srid=4326), geography=True, null=True, srid=4326),
        ),
    ]
