# Generated by Django 3.2.13 on 2022-05-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0039_alter_florafauna_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimaticConditiomm',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='place.place')),
                ('condition', models.CharField(max_length=255)),
                ('climate', models.CharField(choices=[('Tropical', 'Tropical'), ('Dry', 'Dry'), ('Mild', 'Mild'), ('Continental', 'Continental'), ('Polar', 'Polar')], max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
