# Generated by Django 3.2.13 on 2022-05-25 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0040_climaticconditiomm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='is_bookmarked',
        ),
        migrations.AlterField(
            model_name='climaticconditiomm',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='climatic_conditiomm', serialize=False, to='place.place'),
        ),
    ]
