# Generated by Django 3.2.13 on 2022-05-26 06:20

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0042_auto_20220525_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/custom_user/'),
        ),
    ]
