# Generated by Django 4.0.3 on 2022-04-15 17:36

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0042_alter_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='coordinate',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(37.862499, 58.238056, srid=4326), geography=True, null=True, srid=4326),
        ),
    ]
