# Generated by Django 3.2.13 on 2022-05-26 06:44

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0043_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/places/'),
        ),
    ]
