# Generated by Django 4.0.3 on 2022-04-15 17:37

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0043_alter_place_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='coordinate',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(58.238056, 37.862499, srid=4326), geography=True, null=True, srid=4326),
        ),
    ]
