# Generated by Django 3.2.13 on 2022-05-30 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0045_auto_20220528_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscibed_users',
            field=models.ManyToManyField(blank=True, related_name='_place_customuser_subscibed_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
