# Generated by Django 3.2.13 on 2022-05-30 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0046_customuser_subscibed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscibed_users',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscribed_users',
            field=models.ManyToManyField(blank=True, related_name='_place_customuser_subscribed_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
