# Generated by Django 3.2.13 on 2022-05-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0047_auto_20220530_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_social',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
