# Generated by Django 3.2.13 on 2022-06-02 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0048_customuser_image_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscribed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
