# Generated by Django 3.2.13 on 2022-06-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0049_alter_customuser_subscribed_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='subscribed_users',
            new_name='following',
        ),
    ]
