# Generated by Django 3.2.13 on 2022-06-03 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0051_rename_following_customuser_followings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuisine',
            old_name='name',
            new_name='type_cuisine',
        ),
    ]
