# Generated by Django 3.2.13 on 2022-06-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0052_rename_name_cuisine_type_cuisine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typecuisine',
            old_name='type',
            new_name='name',
        ),
    ]
