# Generated by Django 3.2.13 on 2022-06-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0054_auto_20220606_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='place',
        ),
    ]
