# Generated by Django 3.2.13 on 2022-06-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0055_rename_post_comment_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
