# Generated by Django 3.2.13 on 2022-06-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0058_auto_20220607_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image_social',
        ),
    ]
