# Generated by Django 3.2.13 on 2022-06-07 12:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0060_location_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location2',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
