# Generated by Django 3.2.13 on 2022-06-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0061_place_location2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='location2',
        ),
    ]
