# Generated by Django 3.2.13 on 2022-06-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0063_auto_20220612_1011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClimaticConditiomm',
        ),
    ]
