# Generated by Django 3.2.13 on 2022-07-02 12:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0065_auto_20220615_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('writer_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='location', serialize=False, to='place.customuser')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
