# Generated by Django 3.2.13 on 2022-07-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0067_userlocation_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='writer_user',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
