# Generated by Django 3.2.13 on 2022-07-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0071_auto_20220720_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/places/'),
        ),
    ]
