# Generated by Django 3.2.13 on 2022-05-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_achievement_level_increase_to'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ownedachievement',
            unique_together=set(),
        ),
    ]
