# Generated by Django 3.2.13 on 2022-05-12 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achievement', '0003_alter_ownedachievement_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='owner',
            field=models.ManyToManyField(through='achievement.OwnedAchievement', to=settings.AUTH_USER_MODEL),
        ),
    ]
