# Generated by Django 3.2.13 on 2022-05-12 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achievement', '0004_achievement_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ownedachievement',
            unique_together={('writer_user', 'achievement')},
        ),
    ]
