# Generated by Django 3.2.13 on 2022-06-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0005_alter_ownedachievement_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='level_increase_to',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='ownedachievement',
            name='level',
        ),
    ]
