# Generated by Django 3.2.13 on 2022-06-04 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achievement', '0006_auto_20220604_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='owner',
            field=models.ManyToManyField(related_name='achievements', through='achievement.OwnedAchievement', to=settings.AUTH_USER_MODEL),
        ),
    ]
