# Generated by Django 3.2.13 on 2022-06-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0008_alter_achievement_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='level',
            new_name='level_increase_to',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(choices=[('Register', 'Register'), ('Posting 1', 'Posting 1'), ('Posting 3', 'Posting 3'), ('Posting 5', 'Posting 5'), ('Travel destination 3', 'Travel destination 3'), ('Travel destination 5', 'Travel destination 5'), ('Travel destination 7', 'Travel destination 7'), ('Stranger', 'Stranger'), ('Yeti', 'Yeti')], max_length=255, unique=True),
        ),
    ]
