# Generated by Django 3.2.13 on 2022-06-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20220606_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subplacecomment',
            old_name='comment',
            new_name='place_comment',
        ),
    ]
